apiVersion: v1
kind: Service
metadata:
    name: "kubernetescluster-ca56"
    labels:
        app: "kubernetescluster-ca56"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "kubernetescluster-ca56"